services:
  db:
    container_name: db
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  db_data:
