# Generated by Django 4.2 on 2025-02-27 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='itemorder',
            options={'ordering': ['order', 'item'], 'verbose_name': 'Позиция в заказе', 'verbose_name_plural': 'Позиции в заказах'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id', 'status'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Столик', 'verbose_name_plural': 'Столики'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_closed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время закрытия'),
        ),
    ]
