# Generated by Django 4.2 on 2025-03-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_itemorder_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status', 'date_added'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1_READY', 'готово'), ('2_PENDING', 'в ожидании'), ('3_PAID', 'оплачено')], default='2_PENDING', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table', verbose_name='Стол'),
        ),
    ]
