# Generated by Django 4.2 on 2025-03-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_order_options_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Объект активен/актуален'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Объект активен/актуален'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Объект активен/актуален'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Объект активен/актуален')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_closed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время закрытия')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл смену')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shift'),
        ),
    ]
