# Generated by Django 4.2 on 2025-03-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item_is_active_order_is_active_table_is_active_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shift'),
        ),
    ]
