# Generated by Django 4.2 on 2025-03-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date_added'], 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
    ]
